### ISSUE TITLE
Swords don't spawn in map

### ISSUE THREAD

**Issue by altaccountlol** [IrishPacks/ArenaPvP#16] opened 2017-10-17 14:44 UTC
When i  join the server, the swords and paper doesn't spawn. It only spawns after death
Fix?

**Comment by IrishPacks** [comment] 2017-10-17 16:16
Are you using the latest version of Pocketmine and of this plugin? Because using both my phone and Windows 10, I can't reproduce this.

**Comment by altaccountlol** [comment] 2017-10-18 07:00
Yes I am.

**Comment by IrishPacks** [comment] 2017-10-18 08:46
I'll need the commit ids for the Pocketmine version you are running off of as well as the plugin.

**Comment by altaccountlol** [comment] 2017-10-19 14:45
3.0.0-ALPHA9

**Comment by IrishPacks** [comment] 2017-10-19 19:51
That's not a commit ID. A commit ID for Pocketmine would look like this: 0a19a26

**Comment by altaccountlol** [comment] 2017-10-20 17:48
well that is what im using

**Comment by IrishPacks** [comment] 2017-10-20 19:41
Please provide video evidence of this happening or I'll be closing this case.

**Comment by altaccountlol** [comment] 2017-10-21 10:53
I Just fixed it now, you can close this case. But there's another error when I fixed it

**Comment by IrishPacks** [comment] 2017-10-21 15:04
What's the error that you are given, and in what way did you fix it?

**Comment by altaccountlol** [comment] 2017-10-22 10:59
I just had to delete a plugin which interfered with what should go in my hotbar
And it's this

[10:59:07] [Server thread/CRITICAL]: Could not execute task sys\arenapvp\match\MatchHeartbeat: Argument 1 passed to pocketmine\math\Vector3::distance() must be an instance of pocketmine\math\Vector3, null given, called in /root/dropped/PocketMine-MP3/plugins/ArenaPvP-master/src/sys/arenapvp/match/Match.php on line 315
[10:59:07] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\math\Vector3::distance() must be an instance of pocketmine\math\Vector3, null given, called in /root/dropped/PocketMine-MP3/plugins/ArenaPvP-master/src/sys/arenapvp/match/Match.php on line 315" (EXCEPTION) in "src/pocketmine/math/Vector3" at line 189
[10:59:07] [Server thread/DEBUG]: #0 plugins/ArenaPvP-master/src/sys/arenapvp/match/Match(315): pocketmine\math\Vector3->distance(NULL )
[10:59:07] [Server thread/DEBUG]: #1 plugins/ArenaPvP-master/src/sys/arenapvp/match/MatchManager(52): sys\arenapvp\match\Match->tick()
[10:59:07] [Server thread/DEBUG]: #2 plugins/ArenaPvP-master/src/sys/arenapvp/match/MatchHeartbeat(40): sys\arenapvp\match\MatchManager->tickMatches()
[10:59:07] [Server thread/DEBUG]: #3 src/pocketmine/scheduler/TaskHandler(160): sys\arenapvp\match\MatchHeartbeat->onRun(integer 4101)
[10:59:07] [Server thread/DEBUG]: #4 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 4101)
[10:59:07] [Server thread/DEBUG]: #5 src/pocketmine/Server(2506): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 4101)
[10:59:07] [Server thread/DEBUG]: #6 src/pocketmine/Server(2253): pocketmine\Server->tick()
[10:59:07] [Server thread/DEBUG]: #7 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
[10:59:07] [Server thread/DEBUG]: #8 src/pocketmine/Server(1714): pocketmine\Server->start()
[10:59:07] [Server thread/DEBUG]: #9 src/pocketmine/PocketMine(558): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/dropped/PocketMine-MP3/, string /root/dropped/PocketMine-MP3/, string /root/dropped/PocketMine-MP3/plugins/)

**Closed** 2017-10-22 14:50 UTC
Labels: unverified

**Comment by IrishPacks** [comment] 2017-10-22 14:51
That means you probably have a corrupted arena, in which case I'd say to delete it and make a new one and then tell me whether the issue is still present.

**Comment by altaccountlol** [comment] 2017-10-22 18:40
It is still happening, although I did port the maps

**Comment by altaccountlol** [comment] 2017-10-23 16:22
Update : I made my own and yet it is still happening

**Comment by IrishPacks** [comment] 2017-10-23 16:50
Delete the arenas.yml and recreate them, and tell me if it's still recurring, because the error is saying that one of the positions is null.

**Comment by altaccountlol** [comment] 2017-10-23 17:44
it happens when I queue up now

**Comment by IrishPacks** [comment] 2017-10-23 18:04
Send the error and make sure to put 4 backticks(this thing -> ` ) and paste the error and end it with 4 more backticks.

````
It should resemble something like this
````

**Comment by altaccountlol** [comment] 2017-10-24 11:09
-> ` .

**Comment by altaccountlol** [comment] 2017-10-24 11:10
`asdasdasdadasdasdasd`

**Comment by altaccountlol** [comment] 2017-10-24 11:11
`[11:11:30] [Server thread/CRITICAL]: Could not execute task sys\arenapvp\match\MatchHeartbeat: Argument 1 passed to pocketmine\math\Vector3::distance() must be an instance of pocketmine\math\Vector3, null given, called in /root/dropped/PocketMine-MP3/plugins/ArenaPvP-master/src/sys/arenapvp/match/Match.php on line 315
[11:11:30] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\math\Vector3::distance() must be an instance of pocketmine\math\Vector3, null given, called in /root/dropped/PocketMine-MP3/plugins/ArenaPvP-master/src/sys/arenapvp/match/Match.php on line 315" (EXCEPTION) in "src/pocketmine/math/Vector3" at line 189
[11:11:30] [Server thread/DEBUG]: #0 plugins/ArenaPvP-master/src/sys/arenapvp/match/Match(315): pocketmine\math\Vector3->distance(NULL )
[11:11:30] [Server thread/DEBUG]: #1 plugins/ArenaPvP-master/src/sys/arenapvp/match/MatchManager(52): sys\arenapvp\match\Match->tick()
[11:11:30] [Server thread/DEBUG]: #2 plugins/ArenaPvP-master/src/sys/arenapvp/match/MatchHeartbeat(40): sys\arenapvp\match\MatchManager->tickMatches()
[11:11:30] [Server thread/DEBUG]: #3 src/pocketmine/scheduler/TaskHandler(160): sys\arenapvp\match\MatchHeartbeat->onRun(integer 1061)
[11:11:30] [Server thread/DEBUG]: #4 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 1061)
[11:11:30] [Server thread/DEBUG]: #5 src/pocketmine/Server(2506): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 1061)
[11:11:30] [Server thread/DEBUG]: #6 src/pocketmine/Server(2253): pocketmine\Server->tick()
[11:11:30] [Server thread/DEBUG]: #7 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
[11:11:30] [Server thread/DEBUG]: #8 src/pocketmine/Server(1714): pocketmine\Server->start()
[11:11:30] [Server thread/DEBUG]: #9 src/pocketmine/PocketMine(558): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/dropped/PocketMine-MP3/, string /root/dropped/PocketMine-MP3/, string /root/dropped/PocketMine-MP3/plugins/)
`
